version: "3"

services:

  online-wallet-fake:
    image: gwinkamp/online-wallet-fake:latest
    environment:
      - DbConnectionString=Server=postgres;Port=5432;Database=online-wallet-fake;User Id=postgres;Password=postgres;
    ports:
      - 8000:80
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
